version: "3.7"
services: 
  auth:
      container_name: authorize_service
      restart: always
      volumes:
        - ".:/usr/src/IoT_Auth_Service/api"
      build: 
        context: .
        dockerfile: ./auth/src/Dockerfile
      ports:
        - "3002:3002"
      # networks:
      #   - iot_network
      # links:
      #   - db_users
      # depends_on:
      #   - db_users