version: "3.7"
services: 
  auth:
      container_name: authorize_service
      restart: always
      # volumes:
      #   - ".:/usr/src/IoT_Auth_Service/api"
      build: 
        context: .
        dockerfile: ./auth/src/Dockerfile
      ports:
        - "3002:3002"
      # networks:
      #   - iot_network
      # links:
      #   - db_users
      # depends_on:
      #   - db_users
  users:
      container_name: iot_users_service
      restart: always
      # volumes:
      #     - ".:/usr/src/IoT_Users_Service/api"
      build:
        context: .
        dockerfile: ./users/src/Dockerfile
      ports:
          - "3001:3001"
      # links:
      #     - db_users
      # depends_on:
      #     - db_users
  db_iot:
    container_name: postgres_IoT_service
    restart: always
    image: postgres
    ports:
      - ${PSQL_EX_PORT}:${PSQL_IN_PORT}
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      # POSTGRES_HOST: ${PSQL_IN_HOST}
    volumes:
      - ./database/init_tables.sh:/docker-entrypoint-initdb.d/init_tables.sh
      - ./pgdata:/var/lib/postgresql/data